#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "00zdw/Nowoz6"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 2

#define RGB_MATRIX_STARTUP_SPD 60

// Custom QMK here
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

